-- base_dados.sql
-- My Restaurant Adventure
-- Script de criação da base de dados SQLite

PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS ACTION_HISTORY;
DROP TABLE IF EXISTS USER_BUSINESS;
DROP TABLE IF EXISTS BUSINESS_TYPE;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
USERNAME TEXT UNIQUE NOT NULL,
EMAIL TEXT UNIQUE NOT NULL,
PASSWORD_HASH TEXT NOT NULL,
MONEY INTEGER NOT NULL,
REPUTATION INTEGER NOT NULL,
TOTAL_EARNED INTEGER NOT NULL DEFAULT 0,
TOTAL_REPUTATION INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE BUSINESS_TYPE (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
NAME TEXT UNIQUE NOT NULL,
INITIAL_COST INTEGER NOT NULL,
BUILD_TIME INTEGER NOT NULL,
PRODUCTION_TIME INTEGER NOT NULL,
BASE_PROFIT INTEGER NOT NULL,
REPUTATION_BUY INTEGER NOT NULL,
REPUTATION_UPGRADE INTEGER NOT NULL,
MANAGER_NAME TEXT NOT NULL,
MANAGER_MONEY_COST INTEGER NOT NULL,
MANAGER_REP_COST INTEGER NOT NULL
);

CREATE TABLE USER_BUSINESS (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
USER_ID INTEGER NOT NULL,
BUSINESS_TYPE_ID INTEGER NOT NULL,
LEVEL INTEGER NOT NULL,
STATE TEXT NOT NULL,
HAS_MANAGER INTEGER NOT NULL,
BUILD_FINISH_TIME TEXT,
PRODUCTION_FINISH_TIME TEXT,
UPGRADE_FINISH_TIME TEXT,
FOREIGN KEY (USER_ID) REFERENCES USER(ID),
FOREIGN KEY (BUSINESS_TYPE_ID) REFERENCES BUSINESS_TYPE(ID)
);

CREATE TABLE ACTION_HISTORY (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
USER_ID INTEGER NOT NULL,
MESSAGE TEXT NOT NULL,
CREATED_AT TEXT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

INSERT INTO BUSINESS_TYPE (
NAME,
INITIAL_COST,
BUILD_TIME,
PRODUCTION_TIME,
BASE_PROFIT,
REPUTATION_BUY,
REPUTATION_UPGRADE,
MANAGER_NAME,
MANAGER_MONEY_COST,
MANAGER_REP_COST
)
VALUES
(
'Banca de Cachorros',
250,
10,
1,
25,
1,
1,
'Jeff Peso',
2500,
5
),
(
'Café',
1000,
30,
3,
150,
2,
2,
'Mark Lattenberg',
12000,
12
),
(
'Croissanteria',
5000,
60,
5,
800,
4,
4,
'Elon Saint',
60000,
25
),
(
'Hamburgueria',
20000,
90,
8,
3500,
8,
6,
'Warren Burget',
250000,
50
);
